GET http://localhost:3000

###
GET http://localhost:3000/api

###
POST http://localhost:3000/api/sign-up
Content-Type: application/json

{
    "username": "ljack92",
    "password": "Jackol01LJ!",
    "password_repeat" : "Jackol01LJ!"
}

### 
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "ljack92",
    "password": "Jackol01LJ!"
}

###
GET http://localhost:3000/api/secret-route
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxqYWNrOTIiLCJpYXQiOjE3MzUxNTg2MTksImV4cCI6MTczNTE1ODY1OX0.GaCdqfjclYAVh-EAbsAUeS9jdBUN4iJbHfizS0IvUZE

###
GET http://localhost:3000/api/set-cookie

###
GET http://localhost:3000/api/read-cookie


### 
GET http://localhost:3000/api/delete-cookie

###

GET http://localhost:3000/api/delete-tokens

###

POST http://localhost:3000/api/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxqYWNrOTIiLCJ1c2VySWQiOiI0MmVhNmVkNi0wODZkLTQyOGMtYTRjNS04ZTcxOGI3MjVkYzMiLCJpYXQiOjE3MzUxNTg0NzR9.EKToWUSR7ao7F5nC4VxGjDFJWaxGGR4Z5-ZuCCdyq3A"
}

###

DELETE http://localhost:3000/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxqYWNrOTIiLCJ1c2VySWQiOiI0MmVhNmVkNi0wODZkLTQyOGMtYTRjNS04ZTcxOGI3MjVkYzMiLCJpYXQiOjE3MzUxNTg0NzR9.EKToWUSR7ao7F5nC4VxGjDFJWaxGGR4Z5-ZuCCdyq3A"
}